// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libcddmex_path=file('join',['.','./libcdd/libcdd.dll']);
link(libcddmex_path);
libcddmex_path=file('join',['.','libcddmex.dll']);
addinter(libcddmex_path,'libcddmex');
