// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libcddmex_path=file('join',['.','./libcdd/libcdd.so']);
link(libcddmex_path);
libcddmex_path=file('join',['.','libcddmex.so']);
addinter(libcddmex_path,'libcddmex');
